export enum ActionType {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  RESTORE_TOKEN = 'RESTORE_TOKEN',
  SET_USERDATA = 'SET_USERDATA',
  SET_DEPARTMENT = 'SET_DEPARTMENT',
  SET_URL_PREFIX = 'SET_URL_PREFIX',
  RESET_DEPARTMENT = 'RESET_DEPARTMENT',
}
